#!/usr/bin/env node
/**
 * Build-time sync: copies the rendered /subscribe/welcome/ HTML out of the
 * Eleventy build output into a TS module the Worker can import.
 *
 * Run AFTER `npx @11ty/eleventy` and BEFORE deploying the subscribe-checkout
 * Worker. Idempotent — overwrites the existing welcome_shell.ts.
 *
 * Why a build-time sync rather than runtime fetch:
 *   - Zero cold-start latency (the shell is already a JS string in the bundle).
 *   - No origin-fetch loop risk (Worker fetching its own route).
 *   - Single canonical artifact reviewed at brand-gate.
 *
 * If Marketing's shell HTML changes (D1.4 gate feedback or D-CEO-1 visual
 * direction sign-off), re-run Eleventy + this script + redeploy the Worker.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "..", "..", "..");

const SOURCE = resolve(REPO_ROOT, "_site", "subscribe", "welcome", "index.html");
const TARGET = resolve(__dirname, "..", "src", "welcome_shell.ts");

const html = readFileSync(SOURCE, "utf8");

const banner = `// AUTO-GENERATED by scripts/sync_welcome_shell.mjs — DO NOT EDIT BY HAND.
// Source: _site/subscribe/welcome/index.html (Eleventy build output).
// Regenerate via: npm run sync-welcome-shell  (or run the script directly).
//
// The Worker imports WELCOME_SHELL_HTML and feeds it to renderWelcomePage()
// in welcome_render.ts, which mutates the seven \`data-hook="entitlement-*"\`
// nodes via HTMLRewriter based on the resolved Entitlement state.

`;

const escaped = html.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\${/g, "\\${");
const out = `${banner}export const WELCOME_SHELL_HTML = \`${escaped}\`;
`;

writeFileSync(TARGET, out, "utf8");
console.log(`Wrote ${TARGET} (${html.length} bytes of shell HTML)`);
