// AUTO-GENERATED by scripts/sync_welcome_shell.mjs — DO NOT EDIT BY HAND.
// Source: _site/subscribe/welcome/index.html (Eleventy build output).
// Regenerate via: npm run sync-welcome-shell  (or run the script directly).
//
// The Worker imports WELCOME_SHELL_HTML and feeds it to renderWelcomePage()
// in welcome_render.ts, which mutates the seven `data-hook="entitlement-*"`
// nodes via HTMLRewriter based on the resolved Entitlement state.

export const WELCOME_SHELL_HTML = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>You&#39;re in — Elevationary</title>

  <meta name="description" content="Your Elevationary subscription is active. Access begins now.">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="You&#39;re in — Elevationary">
  <meta name="twitter:description" content="Your Elevationary subscription is active. Access begins now.">

  <script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "ProfessionalService",
  "@id": "https://elevationary.com/#org",
  "name": "Elevationary",
  "url": "https://elevationary.com",
  "logo": "https://elevationary.com/assets/elevationary-logo-512.png",
  "description": "Elevationary is an AI consultancy, an AI product company, and a team of AI experts sharing what we know. We install AI-native operating capacity in organizations. We build, run, and own a multi-agent AI system end-to-end. And we operate P4D3 — the executive alignment system for human, agent, and combined teams, built to deliver organizational outcomes.",
  "email": "james.szmak@elevationary.com",
  "areaServed": "Worldwide",
  "knowsAbout": [
    "Artificial Intelligence Strategy",
    "Autonomous AI Agents",
    "AI-Native Operating Capacity",
    "Agentic Commerce",
    "AI Governance and Compliance",
    "P4D3 Executive Alignment",
    "Multi-Agent Workflow Deployment"
  ],
  "sameAs": [
    
    "https://www.linkedin.com/in/jamesszmak/",
    
    "https://twitter.com/ElevationaryAI"
    
  ],
  "founder": {
    "@type": "Person",
    "name": "James Szmak",
    "url": "https://www.elevationary.com/about"
  },
  "contactPoint": [
    {
      "@type": "ContactPoint",
      "contactType": "customer service",
      "email": "james.szmak@elevationary.com",
      "availableLanguage": "English"
    },
    {
      "@type": "ContactPoint",
      "contactType": "sales",
      "email": "james.szmak@elevationary.com",
      "url": "https://agent.elevationary.com/rfp/",
      "availableLanguage": "English",
      "areaServed": "Worldwide"
    }
  ]
}
</script>


  <link rel="icon" href="/assets/elevationary-logo-512.png">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,500;0,600;0,700;1,400&display=swap">
  <link rel="stylesheet" href="/assets/bvp.css">
</head>
<body>
  <main>
    








<section class="el-hero" data-variant="welcome">
  <div class="el-hero__brand">
    <span class="el-hero__wordmark">Elevationary</span>
    <span class="el-hero__accent-line" aria-hidden="true"></span>
  </div>
  <h1 class="el-hero__promise">You&#39;re in. Here&#39;s your access.</h1>
  
  
    

<div data-hook="entitlement-shell" data-state="pending" data-tier="">
  <p data-hook="entitlement-acknowledgment" class="el-welcome__ack">You're in.</p>

  <p class="el-welcome__promise-sub">Intelligence and solutions elevating businesses to AI speeds.</p>

  
  <p data-hook="entitlement-orientation" class="el-welcome__orientation">Your subscription is active. We're loading your tier details now.</p>

  <dl class="el-welcome__details">
    <dt>Tier</dt>
    <dd><span data-hook="entitlement-tier">Your subscription is active. We're loading your tier details now.</span></dd>

    <dt>Access</dt>
    <dd>
      <ul data-hook="entitlement-swimlanes">
        <li>Loading&hellip;</li>
      </ul>
    </dd>

    <dt>Next billing</dt>
    <dd><time data-hook="entitlement-billing-next" datetime="">&mdash;</time></dd>

    <dt>Manage subscription</dt>
    <dd><a data-hook="entitlement-portal-link" href="">Open subscriber portal</a></dd>
  </dl>

  <p data-hook="entitlement-next-action" class="el-welcome__next-action">If the page still shows this message after a minute, your access works regardless &mdash; your first edition will arrive on schedule. Reach us at support@elevationary.com if you'd like us to verify.</p>

  <aside data-hook="entitlement-failure" hidden>
    
    <h2 data-hook="entitlement-failure-headline">We can't read that subscription link.</h2>
    <p data-hook="entitlement-failure-message">
      The link in your welcome email expires after a short window for security reasons. If you clicked an older copy of the email, or the link came from somewhere else, that's the cause.
    </p>
    <p data-hook="entitlement-failure-next-action">
      Two options: forward your most recent welcome email to support@elevationary.com and we'll re-issue access, or sign in at https://elevationary.com/account/ if you already have an account.
    </p>
  </aside>
</div>


  
</section>



<footer class="el-footer el-footer--minimal">
  <span class="el-footer__accent-line" aria-hidden="true"></span>
  <div class="el-footer__inner">
    <div class="el-footer__brand">
      <span class="el-footer__wordmark">Elevationary</span>
      <span class="el-footer__tagline">Elevate your vision</span>
    </div>
    <nav class="el-footer__nav" aria-label="Footer navigation">
      <ul>
        <li><a href="/editions/">Editions</a></li>
        <li><a href="/subscribe/">Subscribe</a></li>
        <li><a href="/about/">About</a></li>
        <li><a href="/contact/">Contact</a></li>
        
        <li><a data-hook="entitlement-portal-link" href="">Account</a></li>
        
      </ul>
    </nav>
    
    <div class="el-footer__legal">
      <p>&copy; 2026 Elevationary. All rights reserved.</p>
      <ul>
        <li><a href="/privacy/">Privacy</a></li>
        <li><a href="/terms/">Terms</a></li>
      </ul>
    </div>
  </div>
</footer>


  </main>
</body>
</html>
`;
